language: java

dist: trusty

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

matrix:
  include:
    - sudo: required
      script:
        - script.sh
      after_failure:
        - echo test
        - cat /var/log/syslog | tail
