name: test 

on:
  push:
    branches-ignore:
      - "test_branch"
    paths:
      - "1.txt"

jobs:
  release:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
